# 06_Unsupervised_Model_Development_LDA

In [30]:
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
import matplotlib.pyplot as plt
from sklearn.decomposition import TruncatedSVD
from sklearn.decomposition import LatentDirichletAllocation
import polars as pl
import joblib
from gensim.corpora import Dictionary

In [31]:
# Load the parquet file
INPUT_PATH = '../data/processed/clustered_narratives.parquet'
df_narratives = pd.read_parquet(
    INPUT_PATH,
    columns=[
        'Complaint ID',
        'processed_narrative'
    ]
)

In [32]:
df_narratives.head()

   Complaint ID                                processed_narrative
0       3442136  claimed delivered package address never receiv...
1       3601853  got brink money pre paid card mail assuming un...
2       3300820  called creditor nelson cruz associate claimed ...
3       3739698  around opened credit card account online capit...
4       3285243  equifax sent credit card suggestion help impro...

In [33]:
print(len(df_narratives))

398004

In [34]:
# # Company stopwords
# company_stopwords = { 'goldman', 'sachs', 'one', 'chase', 'well', 'fargo', 'capital', 'america', 'citibank', 'citi', 'jpmorgan', 'navy', 'federal', 'union'}

In [35]:
# Run Count Vectorizer on 50k sample to save memory
df_lda_sample = df_narratives.sample(
    n=50_000,
    random_state=42
)

count_vectorizer = CountVectorizer(
    min_df=20,
    max_df=0.90,
    max_features=10_000,
    # stop_words=list(company_stopwords)
)

X_count = count_vectorizer.fit_transform(
    df_lda_sample['processed_narrative']
)

print(X_count.shape)

(50000, 6299)

In [36]:
# Run LDA on sample
lda = LatentDirichletAllocation(
    n_components=10,
    learning_method='online',
    random_state=42,
    n_jobs=-1,
    batch_size=2048
)

lda.fit(X_count)

LatentDirichletAllocation(batch_size=2048, learning_method='online', n_jobs=-1,
                          random_state=42)

In [37]:
# Print top terms in the LDA topics
feature_names = np.array(count_vectorizer.get_feature_names_out())

for topic_idx, topic in enumerate(lda.components_):
    top_indices = topic.argsort()[::-1][:15]
    top_terms = feature_names[top_indices]

    print(f'\nTopic {topic_idx}')
    print(', '.join(top_terms))

Topic 0
account, issue, financial, complaint, despite, bank, fund, request, regarding, transaction, customer, matter, service, year, resolution

Topic 1
payment, fee, balance, interest, account, late, pay, month, statement, charge, paid, due, made, amount, charged

Topic 2
account, bank, money, transaction, back, america, day, claim, cash, told, atm, card, time, fund, said

Topic 3
mortgage, loan, insurance, payment, home, escrow, property, tax, year, document, company, received, foreclosure, servicing, letter

Topic 4
account, check, bank, fund, day, would, deposit, told, received, checking, branch, closed, called, call, transfer

Topic 5
charge, dispute, card, well, fargo, claim, merchant, transaction, received, refund, credit, purchase, made, never, letter

Topic 6
credit, card, account, closed, report, limit, score, received, never, application, year, bank, applied, purchase, reward

Topic 7
consumer, credit, information, act, reporting, law, account, violation, federal, right, debt, report, provide, complaint, action

Topic 8
would, told, call, said, called, time, get, back, could, card, one, asked, phone, customer, day

Topic 9
account, chase, one, capital, fraud, bank, number, information, report, fraudulent, name, identity, phone, address, card

In [38]:
# Add dominant topic to the sample dataframe
topic_probs = lda.transform(X_count)

df_lda_sample['dominant_topic'] = topic_probs.argmax(axis=1)
df_lda_sample['topic_probability'] = topic_probs.max(axis=1)

df_lda_sample['dominant_topic'].value_counts().sort_index()

dominant_topic
0    3120
1    5913
2    6946
3    2463
4    7631
5    6028
6    4226
7    2128
8    8139
9    3406
Name: count, dtype: int64

In [39]:
df_lda_sample.head()

,Complaint ID,processed_narrative,dominant_topic,topic_probability
102450,7148773,complain open bank texas day ago received regu...,9,0.383484
78236,5432970,well fargo credit card file police report repo...,5,0.651494
384187,3850335,unresolved issue citibank lasted two month sti...,4,0.590685
272901,12076787,checked account today noticed encoding error c...,4,0.337794
382568,7974309,account saving checking account closed know st...,9,0.541088

In [40]:
# for topic in sorted(df_lda_sample['dominant_topic'].unique()):
#     print(f'\n===== Topic {topic} =====')
#
#     samples = (
#         df_lda_sample[df_lda_sample['dominant_topic'] == topic]
#         .sample(n=3, random_state=42)
#     )
#
#     for text in samples['processed_narrative']:
#         print('\n', text[:500])

In [41]:
# Load in cleaned narratives for the Complaint ID's in the LDA 50k sample
sample_ids = df_lda_sample['Complaint ID'].to_list()

df_readable = (
    pl.scan_parquet(INPUT_PATH)
    .filter(pl.col('Complaint ID').is_in(sample_ids))
    .select([
        'Complaint ID',
        'cleaned_consumer_narrative'
    ])
    .collect()
    .to_pandas()
)

df_lda_sample = df_lda_sample.merge(
    df_readable,
    on='Complaint ID',
    how='left'
)

In [42]:
print(df_lda_sample.columns.tolist())

['Complaint ID', 'processed_narrative', 'dominant_topic', 'topic_probability', 'cleaned_consumer_narrative']

In [43]:
# Print and inspect example narratives in each topic
for topic in sorted(df_lda_sample['dominant_topic'].unique()):
    print(f'\n===== Topic {topic} =====')

    samples = (
        df_lda_sample[df_lda_sample['dominant_topic'] == topic]
        .sample(n=3, random_state=42)
    )

    for text in samples['cleaned_consumer_narrative']:
        print('\n', text[:500])

===== Topic 0 =====

 Dear CFPB Team, I am writing to request an escalation of my unresolved disputes with Chase Bank concerning payments made to REDACTED REDACTED through REDACTED for undelivered services. Chase has rejected my disputes without providing a reasonable explanation, despite clear evidence showing that REDACTED REDACTED failed to deliver the contracted mobile app project. I have made multiple attempts to resolve this issue directly with both Chase and the merchant but have not received any satisfactory

 Subject : Formal Complaint Regarding Fraudulent Transactions Dear SoFi I am writing to formally lodge a complaint regarding REDACTED unauthorized and fraudulent transactions that were made on REDACTED / REDACTED /year> from my SoFi Bank account by REDACTED . The details of these transactions are as follows : Transaction ID : REDACTED Amount : {$19.00} Transaction ID : REDACTED Amount : {$22.00} Both transactions were processed on the same day at REDACTED , terminal location REDACTED , CA, with T

 My consistent effort has been to ensure timely payments on this account, preventing any instances of being overdue. I'm perplexed by the presence of late payment remarks on my accounts. As per 15 USC 1666b - Billing Error, corrections should be implemented.

===== Topic 1 =====

 I am receiving e-mail payment reminders and all my notifications are off, I do not want a payment reminder notification going to e-mail.

 REDACTED / REDACTED /2022. .01 added to savings account. REDACTED / REDACTED /2022 REDACTED added to savings account. Descriptions says credit interest. Checked with the bank. I thought they were subtracted but they were added. Teller did not seem to think that it was due to REDACTED . Concerned that untraceable additions to my account imply access to cause losses, assess charge off. Right now, I don't have any credit open, and I'm paying student loans according to the payment plan selected.

 Hi, This is a follow up to complaint REDACTED . Synchrony Bank did not credit my REDACTED payment. I made the payment on REDACTED_DATE . I then made another payment on REDACTED_DATE because the said I was late. That is when I realized that I made 2 payments on REDACTED_DATE , but 1 was for REDACTED . Sychrony IMMEDIATELY lowered my credit limit from {$10000.00} to {$1900.00}, which was right around what I owe on it under a promotion. So I got in touch with them, and told them what happened. They

===== Topic 2 =====

 Credit Karma froze my account due to a negative balance. After I deposited money to cover the negative balance and more, they still have not reinstated my account. So now I have almost REDACTED dollars sitting there and they wont give me access to it until my case is resolved by some special team. They wont give me any more details only that they will email me when they can.

 On Saturday REDACTED_DATE approximately REDACTED I walked up to the REDACTED REDACTED thru ATM attached to the bank located at REDACTED REDACTED REDACTED REDACTED REDACTED REDACTED REDACTED NM REDACTED to deposit funds into my REDACTED REDACTED acct debit card ending in REDACTED I was traveling from California through New Mexico REDACTED I was unaware REDACTED REDACTED is only located in California. As I attempted to rent a room from a hotel no one accepted cash, so I stopped at PNC to try and d

 I used the ATM machine at Navy Federal in REDACTED , Ca at REDACTED REDACTED REDACTED to withdraw {$200.00} to deposit it into another account on REDACTED_DATE between approximately REDACTED before I could complete the deposit the ATM machine canceled the transaction and only gave me back {$60.00} and kept the remaining {$140.00} dollars. I went directly into the bank to speak with someone and did a ATM claim. However I was told as a non member there is nothing they could do. I was told there is

===== Topic 3 =====

 About 1 year after closing on my home loan, I was invited by certified letter to refinance through the same lender ( Wells Fargo ). I went through the process and provided all of the information requested by the loan officers through a Wells Fargo email portal. At the final stage of the process, they said that the REDACTED insurance policy did not meet their requirements. I was confused because my loan had been approved less than a year before for the same property. I explained that I have no co

 I do not have an escrow account. Therefore, I pay my own property taxes. I paid my property taxes for the tax year of REDACTED in full ( State of Illinois ) in REDACTED of REDACTED . I sent an email with the pdf from the REDACTED REDACTED which showed REDACTED taxes due to the following emails addresses on REDACTED_DATE - REDACTED and REDACTED . I requested written confirmation from Mr. Cooper that they received proof that my taxes for REDACTED were paid in full. I was advised that I would recei

 We requested a REDACTED loan via a brokerage company ( REDACTED ) with settlement date of REDACTED REDACTED_DATE . The loan had a REDACTED funding fee of {$4300.00} paid to REDACTED REDACTED . At the time of our closing I had no veteran REDACTED rating, but have since received a REDACTED REDACTED rating effective back to REDACTED_DATE . Speaking with REDACTED at the VA REDACTED in REDACTED REDACTED he says I'm entitled to a full refund. This is not the main issue. I wish to discuss with the CFPB

===== Topic 4 =====

 On REDACTED / REDACTED /2023 I mailed an endorsed bill, Power of attorney, Federal reserve act 16, and instructionals ( claim of credits ) indicating to apply the principals balance to the principal 's account for each and every billing cycle for set-off. I also instructed the CFO REDACTED REDACTED REDACTED to communicate in writing within 5 business days once instructions are completed. If instructions are not completed, I instructed the CFO REDACTED REDACTED REDACTED to respond in writing with

 I am a Licensed Public Fiduciary and REDACTED REDACTED REDACTED for an individual who has a checking account at PNC Bank located in Arizona. I attempted to close my client 's account as my REDACTED REDACTED for REDACTED states I have the authority to close any account bearing the name of my client. PNC bank is refusing me to close the account. They are asking for an REDACTED REDACTED . I have provided the bank with my Recorded Board of Supervisors Resolution granting me the authority as a licens

 My bank account with SoFi Bank was hacked REDACTED REDACTED / REDACTED /year>, SoFi stated that the fraudster was so relentless that they ( SoFi ) will have to close my account and my account was close REDACTED REDACTED / REDACTED /year>. I've been on the phone with REDACTED from the fraud team and several other customer service representatives ( REDACTED and a few others ) daily since REDACTED REDACTED / REDACTED /year>. During my calls with several representatives I've been getting different i

===== Topic 5 =====

 On REDACTED_DATE , there was an unauthorized charge of {$13.00}. My account went negative then followed by an overdraft fee of {$34.00} from Citibank. I contacted the merchant about the charge, and they refunded me due to their mistake. I called Citibank to dispute the overdraft fee and they refused to approve my request. I explained the situation based on the nature of unauthorized transaction. They did not care at all. They suggested to contact the merchant to reimburse the fee because it was

 REDACTED / REDACTED /2021 I put a refundable deposit down for a REDACTED REDACTED for {$100.00}. In REDACTED / REDACTED /2021 I cancelled the order and the deposit was to refunded within 7-10 days. It was not issued. I disputed the charge and sent the refund documentation to Bank of America REDACTED / REDACTED /2021 and have heard no response. Here is the B of A charge information : REDACTED REDACTED REDACTED REDACTED CA Transaction date : REDACTED / REDACTED /2021 Card type : Visa Transaction t

 I received alerts on my phone that my card was used for Fraud for several REDACTED REDACTED charges I did not make. I reported to chime that my card was used and I requested a new one. I made a claim for a dispute and days later I saw that Chime denied the claim even though I provided pictures.

===== Topic 6 =====

 Its already 2 years since I opened my bank of america credit card account and the inquiry doesnt disappear.

 On REDACTED_DATE ,three(3)fraudulentchargesweremadetomyCITIBankAAdvantageExecutiveMasterCardatthefollowinglocations:{$5400.00}-- REDACTED IL{$840.00}-- REDACTED IL{$780.00}-- REDACTED ILTOTAL:{$7000.00}At REDACTED on REDACTED_DATE ,Ireceivedatextnotification(detailsincludedinattacheddocumentation)askingmeifIattempted{$1900.00}at REDACTED whichIimmediatelyresponded"2''(NO).Ithenreceivedanauto-responsetoopenafrauddispute,whichIdidinlessthan1minute(detailsincludedintheattached)afterreceivingthemess

 American express closed my credit card automatically in a month after annual fee charges apply to my account, but charge me the annual fee for the whole year. My annual fee was charged on REDACTED_DATE for {$230.00}, and american express close my account on REDACTED_DATE . I make a phone call to american express, but they reject to refund the annual fee.

===== Topic 7 =====

 I am Federally Protected Consumer and I have strong reason to believe I have been discriminated against by JPMCB CARD. JPMCB CARD Acct # REDACTED closed my account in REDACTED / REDACTED /2021 they NEVER SENT ME a Pre Adverse Notice, or NEVER SENT ME a Adverse Action Notice. I have strong reason to believe they have discriminated against me under the Equal Credit Opportunity Act ( REDACTED ). JPMCB CARD never informed me of my rights. JPMCB CARD has the obligation to correct action. On REDACTED_

 We have made requests from three national banks we use for a data download of banking date in access of the 18 month limitation set for comma de-liminated data files. When National banks will provide up to 7 years of PDF monthly statements, yet will not provide seven data files for the same data beyond the 18 month limitation. What is the logic? In both cases, they have to go to off-line storage to access the data. In the data format, they will only have to retrieve up to seven annual data files

 In accordance with the Fair Credit Reporting Act, this creditor has violated my rights. Under 15 USC 1681 602 states I have the right to privacy. 15 USC 1681 604a ( 2 ), it also states a consumer reporting agency can not furnish an account without my written instructions. Under 15 USC 1666b, a creditor may not treat a payment on a credit card account under an open end consumer credit plan as late for any purpose.

===== Topic 8 =====

 I got an email from capital one saying that I should use my credit card or else they would close it because it was not being used. So, I promptly went ahead and used the card when I went to fill up gas. I had not used the card in a bit as I had lost it while moving and never seen it since. I had also gone into a branch in the interim and they had promised me that they had sent out a card. I went to the grocery store today, and my card did not work! On the screen came up something that said DO NO

 I had a Simple account that got transitioned over to BBVA. I can not access my account online and their customer service is atrocious. I was on hold for 30 minutes and ended up getting hung up on. Tried again and have been on hold for two hours with no end in sight.

 So maybe it was early REDACTED end of REDACTED I was in the bealls store making a purchase when cashier asked if I would like to apply for a credit card I was like sure applied got approved the cashier assured me that I would get the card within 7 to 10 business days so I used the temp card or paper to make REDACTED purchase of {$63.00} I wanted almost a month never received a card so called don't remember who I talk to I explain to them I never received a card so that said no a problem we can f

===== Topic 9 =====

 On REDACTED / REDACTED /2021, a purchase was made at REDACTED REDACTED REDACTED , a jewelry store in REDACTED , FL for over {$18000.00} using my chase business credit card. I was not in REDACTED , FL on that date and I didn't make the purchase. I learned about the fraud on the same morning and contacted Chase immediately to alert them. I also called the merchant to alert them as to what happened. Later that day I received a phone call from a REDACTED REDACTED with the REDACTED County Sheriff 's

 I recently opened a credit card with CapitalOne under my current legal name which is associated with my Social Security Number and is listed on my Social Security Card, Drivers License, Passport, and Birth Certificate. Without me requesting them to and without me doing so, CapitalOne listed the account owner under a different name which was my former legal name. They did not explain why this happened. I am highly concerned with the privacy and safety of my account when an application I submitted

 A joint account was used to cover overdraft fees from my individual account without any consent from myself or the joint account holder. I was told that the joint account has 200 % liability.

In [44]:
tokenized_docs = (
    df_lda_sample['processed_narrative']
    .str.split()
    .tolist()
)

dictionary = Dictionary(tokenized_docs)

In [45]:
topics = []

for topic in lda.components_:

    top_indices = topic.argsort()[::-1][:15]

    topics.append(
        [feature_names[i] for i in top_indices]
    )

In [46]:
from gensim.models.coherencemodel import CoherenceModel

coherence_model = CoherenceModel(
    topics=topics,
    texts=tokenized_docs,
    dictionary=dictionary,
    coherence='c_v'
)

coherence_score = coherence_model.get_coherence()

print(f'Coherence Score: {coherence_score:.4f}')

Coherence Score: 0.4818

In [47]:
# Add Topic Probabilities as a Feature
topic_features = pd.DataFrame(
    topic_probs,
    columns=[
        f'topic_{i}_prob'
        for i in range(topic_probs.shape[1])
    ]
)

df_lda_sample = pd.concat(
    [df_lda_sample.reset_index(drop=True),
     topic_features.reset_index(drop=True)],
    axis=1
)

df_lda_sample.head()

,Complaint ID,processed_narrative,dominant_topic,topic_probability,cleaned_consumer_narrative,topic_0_prob,topic_1_prob,topic_2_prob,topic_3_prob,topic_4_prob,topic_5_prob,topic_6_prob,topic_7_prob,topic_8_prob,topic_9_prob
0,7148773,complain open bank texas day ago received regu...,9,0.383484,I have a complain open No REDACTED against Ban...,0.000971,0.000971,0.000971,0.113284,0.000971,0.000971,0.000971,0.114072,0.383333,0.383484
1,5432970,well fargo credit card file police report repo...,5,0.651494,Wells Fargo credit card {$3500.00} REDACTED / ...,0.005883,0.005883,0.005884,0.005883,0.005883,0.651494,0.005885,0.005883,0.005884,0.301438
2,3850335,unresolved issue citibank lasted two month sti...,4,0.590685,My unresolved issues with CitiBank have now la...,0.025169,0.000198,0.000198,0.000198,0.590685,0.057723,0.112084,0.000198,0.162737,0.050810
3,12076787,checked account today noticed encoding error c...,4,0.337794,I checked my account today and noticed that th...,0.000893,0.139639,0.301211,0.000893,0.337794,0.215998,0.000893,0.000893,0.000893,0.000893
4,7974309,account saving checking account closed know st...,9,0.541088,My account savings and checking account was cl...,0.006251,0.006251,0.006252,0.006251,0.408902,0.006252,0.006251,0.006251,0.006251,0.541088

In [48]:
# Identify remaining records outside of initial LDA sample
remaining_mask = ~df_narratives['Complaint ID'].isin(
    df_lda_sample['Complaint ID']
)

df_lda_remaining = df_narratives.loc[
    remaining_mask,
    ['Complaint ID', 'processed_narrative']
].copy()

print(f'Remaining records: {len(df_lda_remaining):,}')

Remaining records: 348,004

In [49]:
# Apply LDA to the remaining records without re-training
batch_size = 50_000
feature_batches = []

for start in range(0, len(df_lda_remaining), batch_size):
    end = min(start + batch_size, len(df_lda_remaining))

    print(f'Processing rows {start:,} to {end:,}...')

    batch = df_lda_remaining.iloc[start:end]

    X_batch = count_vectorizer.transform(
        batch['processed_narrative']
    )

    topic_probs = lda.transform(X_batch)

    topic_features = pd.DataFrame(
        topic_probs,
        columns=[
            f'topic_{i}_prob'
            for i in range(topic_probs.shape[1])
        ]
    )

    topic_features['Complaint ID'] = batch['Complaint ID'].values
    topic_features['dominant_topic'] = topic_probs.argmax(axis=1)

    feature_batches.append(topic_features)

Processing rows 0 to 50,000...
Processing rows 50,000 to 100,000...
Processing rows 100,000 to 150,000...
Processing rows 150,000 to 200,000...
Processing rows 200,000 to 250,000...
Processing rows 250,000 to 300,000...
Processing rows 300,000 to 348,004...

In [50]:
# Write fitted Count Vectorizer and LDA to file
joblib.dump(
    count_vectorizer,
    'count_vectorizer.pkl'
)

joblib.dump(
    lda,
    'lda_model.pkl'
)

['lda_model.pkl']

In [51]:
#Concatenate the rows
lda_features_remaining = pd.concat(
    feature_batches,
    ignore_index=True
)

# Optional: put Complaint ID first
cols = (
    ['Complaint ID', 'dominant_topic']
    + [
        col for col in lda_features_remaining.columns
        if col.startswith('topic_')
    ]
)

lda_features_remaining = lda_features_remaining[cols]

In [52]:
lda_features_remaining.head()

,Complaint ID,dominant_topic,topic_0_prob,topic_1_prob,topic_2_prob,topic_3_prob,topic_4_prob,topic_5_prob,topic_6_prob,topic_7_prob,topic_8_prob,topic_9_prob
0,3442136,5,0.001205,0.021625,0.001205,0.001205,0.105470,0.837037,0.028637,0.001205,0.001205,0.001205
1,3601853,8,0.004349,0.004349,0.004350,0.205481,0.004349,0.004349,0.246325,0.004348,0.517751,0.004349
2,3300820,8,0.001852,0.001852,0.001852,0.001852,0.001852,0.001852,0.149823,0.130912,0.421510,0.286641
3,3739698,8,0.001075,0.001075,0.099669,0.001075,0.001076,0.001076,0.138743,0.001075,0.425832,0.329303
4,3285243,6,0.004167,0.004168,0.004168,0.004167,0.004168,0.004168,0.829646,0.004167,0.137015,0.004167

In [53]:
# Write to parquet
OUTPUT_PATH = '../data/processed/lda_features.parquet'

lda_features_remaining.to_parquet(
    OUTPUT_PATH,
    index=False
)

print(lda_features_remaining.shape)

(348004, 12)